# Generated by Django 4.2.7 on 2023-12-02 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('company_name', models.CharField(max_length=100, verbose_name="Dénomination sociale de l'entreprise")),
                ('address', models.TextField(verbose_name='Adresse')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Code postal')),
                ('city', models.CharField(max_length=50, verbose_name='Ville')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Numéro de téléphone')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
