# Generated by Django 4.2.7 on 2023-12-04 10:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_repairstore_uniquereference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recycler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name="Dénomination sociale de l'entreprise")),
                ('address', models.TextField(verbose_name='Adresse')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Code postal')),
                ('city', models.CharField(max_length=50, verbose_name='Ville')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Numéro de téléphone')),
                ('date_joined', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_us', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenBrand',
            fields=[
                ('screenbrand', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['screenbrand'],
            },
        ),
        migrations.CreateModel(
            name='ScreenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenmodel', models.CharField(max_length=50)),
                ('is_oled', models.BooleanField(default=False)),
                ('is_wanted', models.BooleanField(default=False)),
                ('screenbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.screenbrand')),
            ],
            options={
                'ordering': ['screenbrand', 'screenmodel'],
            },
        ),
        migrations.CreateModel(
            name='RecyclerPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('Fully Broken', 'Fully Broken'), ('Aftermarket', 'Aftermarket')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.recycler')),
                ('screenbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.screenbrand')),
                ('screenmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.screenmodel')),
            ],
            options={
                'unique_together': {('recycler', 'screenbrand', 'screenmodel', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='BrokenScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attributed', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('recycler_prices', models.ManyToManyField(related_name='broken_screens', to='listings.recyclerpricing')),
                ('repairShop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.repairstore')),
                ('screenbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.screenbrand')),
                ('screenmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.screenmodel')),
                ('uniquereference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='listings.uniquereference')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
