# Generated by Django 4.2.7 on 2023-12-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_repairshop_brokenscreen_repairstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokenscreen',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('Fully Broken', 'Fully Broken'), ('Aftermarket', 'Aftermarket')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
