# Generated by Django 4.2.7 on 2023-12-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_brokenscreen_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokenscreen',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
