# Generated by Django 5.0 on 2023-12-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_brokenscreen_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokenscreen',
            name='price',
        ),
        migrations.AddField(
            model_name='brokenscreen',
            name='is_diag_done',
            field=models.BooleanField(default=False),
        ),
    ]
