# Generated by Django 5.0 on 2023-12-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_brokenscreen_price_brokenscreen_is_diag_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokenscreen',
            name='diag_response_1',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokenscreen',
            name='diag_response_2',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokenscreen',
            name='diag_response_3',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokenscreen',
            name='diag_response_4',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokenscreen',
            name='diag_response_5',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokenscreen',
            name='diag_response_6',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokenscreen',
            name='diag_response_7',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokenscreen',
            name='diag_response_8',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokenscreen',
            name='diag_response_9',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
