# Generated by Django 5.0 on 2023-12-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_brokenscreen_diag_response_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokenscreen',
            name='diag_response_1',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='brokenscreen',
            name='diag_response_2',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='brokenscreen',
            name='diag_response_3',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='brokenscreen',
            name='diag_response_4',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='brokenscreen',
            name='diag_response_5',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='brokenscreen',
            name='diag_response_6',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='brokenscreen',
            name='diag_response_7',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='brokenscreen',
            name='diag_response_8',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='brokenscreen',
            name='diag_response_9',
            field=models.BooleanField(null=True),
        ),
    ]
