# Generated by Django 5.0 on 2023-12-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_brokenscreen_diag_response_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokenscreen',
            name='grade',
            field=models.CharField(choices=[('', 'Select Grade'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('Fully Broken', 'Fully Broken'), ('Aftermarket', 'Aftermarket')], default='', max_length=20),
        ),
    ]
