# Generated by Django 5.0 on 2023-12-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_brokenscreen_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brokenscreen',
            old_name='recycler_prices',
            new_name='quotations',
        ),
    ]
