# Generated by Django 5.0 on 2023-12-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_rename_recycler_prices_brokenscreen_quotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokenscreen',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
