# Generated by Django 5.0 on 2023-12-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_brokenscreen_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokenscreen',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
