# Generated by Django 5.0 on 2023-12-27 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_brokenscreen_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokenscreen',
            name='recycler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.recycler'),
        ),
    ]
