# Generated by Django 5.0 on 2023-12-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_brokenscreen_recycler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recycler',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name="Dénomination sociale de l'entreprise"),
        ),
    ]
