# Generated by Django 5.0 on 2023-12-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_alter_recycler_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycler',
            name='company_raison_social',
            field=models.CharField(blank=True, max_length=100, verbose_name='Raison sociale'),
        ),
        migrations.AddField(
            model_name='recycler',
            name='payment_delay',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recycler',
            name='payment_method',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recycler',
            name='shipping_fee',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recycler',
            name='siren',
            field=models.CharField(default=1, max_length=15, verbose_name='Numéro siren'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recycler',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
