# Generated by Django 5.0 on 2023-12-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_recycler_company_raison_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recycler',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recycler',
            name='shipping_fee',
            field=models.CharField(max_length=50),
        ),
    ]
