# Generated by Django 5.0 on 2024-01-01 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_remove_repairstore_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('date_shipped', models.DateTimeField(auto_now_add=True)),
                ('is_received', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='brokenscreen',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brokenscreen',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.package'),
        ),
    ]
