# Generated by Django 5.0 on 2024-01-01 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_package_brokenscreen_is_shipped_brokenscreen_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokenscreen',
            name='package',
        ),
        migrations.AddField(
            model_name='package',
            name='broken_screens',
            field=models.ManyToManyField(to='listings.brokenscreen'),
        ),
        migrations.AddField(
            model_name='package',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='recycler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.recycler'),
            preserve_default=False,
        ),
    ]
