# Generated by Django 5.0 on 2024-01-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_remove_brokenscreen_package_package_broken_screens_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brokenscreen',
            old_name='is_shipped',
            new_name='is_packed',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='is_received',
            new_name='is_shipped',
        ),
    ]
