# Generated by Django 5.0 on 2024-01-02 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_rename_is_shipped_brokenscreen_is_packed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brokenscreen',
            old_name='is_packed',
            new_name='is_shipped',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='is_paid',
            new_name='is_received',
        ),
        migrations.RemoveField(
            model_name='package',
            name='broken_screens',
        ),
        migrations.RemoveField(
            model_name='package',
            name='is_shipped',
        ),
        migrations.RemoveField(
            model_name='package',
            name='recycler',
        ),
        migrations.AddField(
            model_name='brokenscreen',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.package'),
        ),
    ]
