# Generated by Django 5.0 on 2024-01-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_rename_is_packed_brokenscreen_is_shipped_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brokenscreen',
            old_name='is_shipped',
            new_name='is_packed',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='is_received',
            new_name='is_paid',
        ),
        migrations.AddField(
            model_name='package',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
