# Generated by Django 5.0 on 2024-01-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_rename_is_shipped_brokenscreen_is_packed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='uniquereferences',
            field=models.ManyToManyField(related_name='packages', to='listings.uniquereference'),
        ),
    ]
