# Generated by Django 5.0 on 2024-01-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_package_uniquereferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokenscreen',
            name='package',
        ),
        migrations.RemoveField(
            model_name='package',
            name='uniquereferences',
        ),
        migrations.AddField(
            model_name='package',
            name='brokenscreens',
            field=models.ManyToManyField(related_name='packages', to='listings.brokenscreen'),
        ),
    ]
