# Generated by Django 5.0 on 2024-01-04 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_package_total_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokenScreenPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brokenscreen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.brokenscreen')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.package')),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='brokenscreens',
            field=models.ManyToManyField(related_name='packages', through='listings.BrokenScreenPackage', to='listings.brokenscreen'),
        ),
    ]
