# Generated by Django 5.0 on 2024-01-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_brokenscreenpackage_alter_package_brokenscreens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='brokenscreens',
        ),
        migrations.AddField(
            model_name='package',
            name='brokenscreens_temp',
            field=models.ManyToManyField(related_name='packages_temp', to='listings.brokenscreen'),
        ),
    ]
