# Generated by Django 5.0 on 2024-01-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_remove_package_brokenscreens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='brokenscreens_temp',
        ),
    ]
