# Generated by Django 4.2.7 on 2024-02-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_brokenscreen_diag_question_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
