# Generated by Django 4.2.7 on 2024-02-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0032_remove_package_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonneNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
