# Generated by Django 4.2.7 on 2024-02-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_abonnenewsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenmodel',
            name='is_3dtouch',
            field=models.BooleanField(default=False),
        ),
    ]
