# Generated by Django 4.2.7 on 2024-02-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_screenmodel_is_3dtouch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenmodel',
            name='is_3dtouch',
        ),
    ]
