# Generated by Django 4.2.7 on 2024-02-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0037_remove_screenmodel_is_3dtouch'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenmodel',
            name='is_3dtouch',
            field=models.BooleanField(default=False),
        ),
    ]
