# Generated by Django 4.2.7 on 2024-02-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0038_screenmodel_is_3dtouch'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokenscreen',
            name='diag_question_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokenscreen',
            name='diag_response_10',
            field=models.BooleanField(null=True),
        ),
    ]
